build:
  pre:
    - echo "Starting Render deploy"
  main:
    - echo "Deploying to Render"
    - git push render master

version: 2.0
# render.yaml

# The language and version of the runtime
language: python
python_version: 3.8

# The command to start the application
commands:
  start: |
    pip install -r requirements.txt
    export TOKEN="${{ secrets.TOKEN }}"
    python discord/main.py
env:
  TOKEN: ${{ secrets.TOKEN }}
